# Workflow to build and test wheels.
# To work on the wheel building infrastructure on a fork, comment out:
#
# if: github.repository == 'numpy/numpy'
#
# in the get_commit_message job. Be sure to include [wheel build] in your commit
# message to trigger the build. All files related to wheel building are located
# at tools/wheels/
# Alternatively, you can add labels to the pull request in order to trigger wheel
# builds.
# The labels that trigger builds are:
# 36 - Build(for changes to the building process,
# 14 - Release(ensure wheels build before release)
on:
  workflow_dispatch:
name: Nightly Wheel builder

  upload_anaconda:
    name: Upload to Anaconda
    runs-on: ubuntu-latest
    # The artifacts cannot be uploaded on PRs
    if: github.event_name != 'pull_request'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: |
            setup.cfg
      - name: Try building with Python build
      if: runner.os != 'Windows'  # setup.py does not support sdist on Windows
      run: |
        python -m build

      - name: Upload wheel 
        uses: scientific-python/upload-nightly-wheel
        with: 
          artifact-names: dist/*.whl
          anaconda-nightly-upload-token: ${secrets.UPLOAD_TOKEN}
